site_name: ReachView
theme_dir: material
site_favicon: favicon.ico
repo_url: https://github.com/emlid/reachview-docs
extra:
  palette:
    primary: 'light blue'
    accent: 'light blue'
  logo: 'img/logo.png'
  social:
    - type: 'github'
      link: 'https://github.com/emlid'
    - type: 'twitter'
      link: 'https://twitter.com/emlidtech'
    - type: 'facebook'
      link: 'https://facebook.com/emlidtech' 
  google_analytics:
    - 'UA-49508097-6'
    - 'auto'

  copyright: 
    - 'Copyright & copy; 2016 - 2017 Emlid Ltd.'

markdown_extensions:
    - markdown.extensions.admonition
    - markdown.extensions.codehilite(guess_lang=false)
    - markdown.extensions.def_list
    - markdown.extensions.footnotes
    - markdown.extensions.meta
    - markdown.extensions.toc(permalink=true)
    - pymdownx.arithmatex
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic   
   
pages:
- ReachView app:
  - Introduction: reachview.md
  - Settings: reachview-settings.md
  - Status: reachview-status.md
  - 'RTK settings': 'reachview-rtk-settings.md'
  - 'Correction input': 'reachview-correction-input.md'
  - 'Position output': 'reachview-position-output.md'
  - 'Base mode': 'reachview-base-mode.md'
  - 'Logging': 'reachview-logging.md'
  - 'Camera control': 'reachview-camera-control.md'
  - 'Wi-fi/Bluetooth': 'reachview-connectivity.md'
  - 'Firmware reflashing': 'reachview-firmware-reflashing.md'
  - 'LED status': 'reachview-led-status.md'
  - 'Changelogs': 'reachview-changelogs.md'
- ReachView tutorials:
  - 'Bluetooth output and Android mock location': 'reachview-lefebure.md'
